[project]
name = "brainvisa-forge"
version = "0.1.0"
description = "Build BrainVISA projects from sources"
authors = ["BrainVISA team <contact@brainvisa.info>"]
channels = ["conda-forge", "https://brainvisa.info/download/conda"]
platforms = ["linux-64"]

[tasks]
toto = "echo test"

[activation]
scripts=["activate.sh"]

[feature.brainvisa-forge.dependencies]
python = ">3.9"
toml = ">=0.10.2"
six = ">=1.16.0"
git = ">=2.44.0"
pip = ">=24.0"
cmake = ">=3.28.3"
sphinx = ">=7.2.6"
pytest = ">=8.0.2"
rattler-build = "*"

[feature.populse-db.dependencies]
python = "<=3.10"
python-dateutil = "*"
lark-parser = ">= 0.7.0"


[feature.soma-python.dependencies]
pydantic = "<2"

[environments]
default = [
    "brainvisa-forge",
    "populse-db",
    "soma-python"
    ]
