[project]
name = "brainvisa-forge"
version = "0.1.0"
description = "Build BrainVISA projects from sources"
authors = ["BrainVISA team <contact@brainvisa.info>"]
channels = ["conda-forge", "https://brainvisa.info/download/conda"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = ">=3.12,<3.13"
toml = ">=0.10.2,<0.11"
six = ">=1.16.0,<1.17"
git = ">=2.44.0,<2.45"
pip = ">=24.0,<25"
cmake = ">=3.28.3,<3.29"

[activation]
scripts=["activate.sh"]
