[project]
name = "soma-forge"
version = "0.1.0"
description = "Build BrainVISA projects from sources"
authors = [ "BrainVISA team <contact@brainvisa.info>",]
channels = [ "conda-forge"]
platforms = [ "linux-64",]

[activation]
scripts = [ "activate.sh",]

[environments]
default = [ "soma-forge"]

[dependencies]


[tasks.setup]
cmd = "python -m brainvisa_forge setup"

[tasks.build]
cmd = "python -m brainvisa_forge build"

[tasks.forge]
cmd = [ "python", "-m", "brainvisa_forge", "forge",]

[feature.soma-forge.dependencies]
python = ">3.9"
ipython = "*"
toml = "*"
pyaml = "*"
git = "*"
cmake = "*"
gcc = "*"
sphinx = "*"
pytest = "*"
rattler-build = "*"
